### ISSUE TITLE
"there are no tokens so there can be no transfer" OR all the tokens successfully transferred?

### ISSUE THREAD

**Issue by stefek99** [walleth/contracts#1]
For every tokens in existence, you are successful?

True or false?

LOL

**Comment by ligi** [comment]
;_)

but closing this as it is not really actionable ..

**Comment by stefek99** [comment]
I think the method should return true, LOL...

Shapeshift responded to `ether:` vs `ethereum:` issue - https://twitter.com/ShapeShift_io/status/1017825885716713485

People in crypto are nice, so much collaboration and support everywhere...

**Comment by ligi** [comment]
YAY - thanks so much for passing this on!
